import Head from 'next/head'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={`${styles.navbar}`}>
        <ul>

          <Link href='/'><li>Home</li></Link>
          <Link href='/about'><li>About</li></Link>
          <Link href='/blog'><li>Blog</li></Link>
          <Link href='/contact'><li>Contact</li></Link>
        </ul>
      </nav>
      {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${styles.company}`}>
          <div className={`${styles.backgroundBlur}`}></div>
          <h1 className={`${styles.head}`}>Hunding Coders</h1>
          <p className={`${styles.descr}`}>A blog Website using NextJs</p>
        </div>

        <div className={`${styles.blogs}`}>
          <h2>Popular Blogs</h2>
          <div className={`${styles.blogItem}`}>
            <h3 className>How to Learn Js in 2023</h3>
            <p>Javascript is the language is used to desgign logic for your website</p>
          </div>
          <div className={`${styles.blogItem}`}>
            <h3>How to Learn Js in 2023</h3>
            <p>Javascript is the language is used to desgign logic for your website</p>
          </div>
          <div className={`${styles.blogItem}`}>
            <h3>How to Learn Js in 2023</h3>
            <p>Javascript is the language is used to desgign logic for your website</p>
          </div>
        </div>
      </main>
    </>
  )
}
